# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _ast

import flatbuffers

class Element(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsElement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Element()
        x.Init(buf, n + offset)
        return x

    # Element
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Element
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Element
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Element
    def Tail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

    # Element
    def Child(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Element import Element
            obj = Element()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Element
    def ChildLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Element
    def Extra(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Anonymous0 import Anonymous0
            obj = Anonymous0()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ElementStart(builder): builder.StartObject(5)
def ElementAddKind(builder, kind): builder.PrependInt32Slot(0, kind, 0)
def ElementAddText(builder, text): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def ElementAddTail(builder, tail): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tail), 0)
def ElementAddChild(builder, child): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(child), 0)
def ElementStartChildVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ElementAddExtra(builder, extra): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(extra), 0)
def ElementEnd(builder): return builder.EndObject()
