# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _Unit

class LanguageType(object):
    ALL = 0
    OO = 1
    CXX = 2
    C = 3
    C_FAMILY = 4
    Java = 5
    CSHARP = 6
    OBJECTIVE_C = 7

