# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _Literal

class LiteralType(object):
    number_type = 0
    char_type = 1
    string_type = 2
    boolean_type = 3
    null_type = 4

