# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _Element

import flatbuffers

class Literal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLiteral(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Literal()
        x.Init(buf, n + offset)
        return x

    # Literal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Literal
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def LiteralStart(builder): builder.StartObject(1)
def LiteralAddType(builder, type): builder.PrependInt32Slot(0, type, 0)
def LiteralEnd(builder): return builder.EndObject()
